#! /usr/bin/env bash
set -euo pipefail

port="$1"

mkdir -p .dev

cd rust
wasm-pack build --debug --mode no-install --target web

cd ../

cp -R rust/pkg .dev/
cp html/*.html .dev/

nix-shell -p python3 --run "python3 -m http.server $port --directory .dev"
